from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def expected_snp_nodes(port_count: int) -> list[str]:
    return [f"p{i}" for i in range(1, port_count + 1)] + ["0"]


def expected_lanepair_nodes(port_count: int) -> list[str]:
    nodes: list[str] = []
    for lane in range(port_count // 2):
        nodes.extend([f"tx{lane}", f"rx{lane}"])
    return nodes + ["0"]


def check_netlist(netlist: Path, port_count: int | None, allow_internal_snp_nodes: bool = False) -> dict[str, object]:
    if not netlist.exists():
        return {"ok": False, "path": str(netlist), "error": "netlist file does not exist"}
    text = read_text(netlist)
    snp_lines = [line.strip() for line in text.splitlines() if re.match(r"^S\d+P:", line.strip(), re.IGNORECASE)]
    result: dict[str, object] = {"ok": True, "path": str(netlist), "snp_lines": snp_lines}
    if port_count is None or not snp_lines:
        result["ok"] = bool(snp_lines)
        if not snp_lines:
            result["error"] = "no fixed SnP netlist line found"
        return result

    expected = expected_snp_nodes(port_count)
    expected_lane = expected_lanepair_nodes(port_count) if port_count % 2 == 0 else []
    line = snp_lines[0]
    tokens = line.split()
    nodes = tokens[1 : 1 + port_count + 1]
    result["nodes"] = nodes
    result["expected_nodes"] = expected
    if expected_lane:
        result["expected_lanepair_nodes"] = expected_lane
    result["node_count_ok"] = len(nodes) == port_count + 1
    result["file_token_ok"] = not any("File=@" in token or 'File="@' in token for token in tokens)
    result["ok"] = nodes == expected or nodes == expected_lane
    if not result["ok"]:
        if allow_internal_snp_nodes and result["node_count_ok"] and result["file_token_ok"]:
            result["ok"] = True
            result["warning"] = (
                "SnP nodes use ADS internal net names. Treat this as valid only "
                "when a separate schematic term-number/label audit confirms port order."
            )
        else:
            result["error"] = "SnP node order does not match p1..pN 0 or tx/rx lane-pair order"
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate an ADS workspace generated by the SIPI harness.")
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--netlist", type=Path)
    parser.add_argument("--port-count", type=int)
    parser.add_argument(
        "--allow-internal-snp-nodes",
        action="store_true",
        help="Accept ADS-generated internal SnP net names when node count and file token are valid; requires a separate port-label audit.",
    )
    parser.add_argument("--summary", type=Path, required=True)
    args = parser.parse_args()

    workspace = args.workspace.resolve()
    checks: dict[str, object] = {
        "workspace": str(workspace),
        "workspace_exists": workspace.exists() and workspace.is_dir(),
        "workspace_ads_placeholder_absent": not (workspace / "workspace.ads").exists(),
        "lib_defs_exists": (workspace / "lib.defs").exists(),
        "cds_lib_exists": (workspace / "cds.lib").exists(),
        "data_dir_exists": (workspace / "data").exists(),
        "reports_dir_exists": (workspace / "reports").exists(),
    }

    if args.netlist:
        checks["netlist"] = check_netlist(args.netlist.resolve(), args.port_count, args.allow_internal_snp_nodes)

    ok = all(value is True for key, value in checks.items() if key not in {"workspace", "netlist"})
    if "netlist" in checks:
        ok = ok and bool(checks["netlist"].get("ok"))  # type: ignore[union-attr]
    checks["ok"] = ok

    args.summary.parent.mkdir(parents=True, exist_ok=True)
    args.summary.write_text(json.dumps(checks, indent=2), encoding="utf-8")
    print(json.dumps(checks, indent=2))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
