from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ADS = Path(r"C:\Program Files\Keysight\ADS2026_Update2")
DEFAULT_TEMPLATE = ROOT / "outputs" / "ads_channel_sim" / "example_extract" / "ChannelSimulatorTutorial_wrk"
DEFAULT_S2P = (
    ROOT
    / "outputs"
    / "hfss3dlayout_import"
    / "microstrip_50ohm_fr4_1p6_hfss3dlayout.s2p"
)
DEFAULT_WORKSPACE = ROOT / "outputs" / "ads_channel_sim" / "microstrip_4gbps_wrk"
DEFAULT_BIT_RATE_GBPS = 4.0
DEFAULT_VHIGH = 1.1


def slash(path: Path) -> str:
    return str(path).replace("\\", "/")


def make_netlist(s2p_name: str, bit_rate_gbps: float, vhigh: float) -> str:
    return f"""; ADS ChannelSim netlist generated by create_ads_channel_workspace.py
; Channel: HFSS 3D Layout microstrip 50-ohm FR4 coupon, 2-port Touchstone
; Data rate: {bit_rate_gbps:g} Gbps NRZ

Options ResourceUsage=yes UseNutmegFormat=no EnableOptim=no \\
 TopDesignName="SIPI_microstrip_4gbps_lib:microstrip_4gbps:schematic" \\
 DcopOutputNodeVoltages=yes DcopOutputPinCurrents=yes

ChannelSim:ChannelSim1 Type="FastConvolution" NumberOfBits=2048 \\
 ToleranceMode=1 EnforcePassivity=yes MaxImpulseLength=4096 \\
 NumberTimePtPerUI=64 BlockSize=4096 StatusLevel=2 \\
 AntiAliasingWindow=1 ImpLFEOn=yes ImpCache=yes

#load "python","TDM_Eye"
ComponentWithNodes:Eye_Probe1 rx Type="ModelExtractor" Module="Eye" \\
 Save_LevelMean=yes Save_HeightAtBER=yes Save_Level1=yes Save_JitterRMS=yes \\
 Save_Density=yes Save_RiseTime=yes Save_Height=yes Save_Level0=yes \\
 Save_Width=yes Save_CheckMaskViolation=no Save_SNR=yes Save_Amplitude=yes \\
 Save_HeightDB=yes Save_FallTime=yes Save_WidthAtBER=yes Save_JitterPP=yes \\
 Save_Bathtub=yes Save_Waveform=yes Save_Contour=yes Save_CrossingLevel=yes \\
 Save_ClockSignal=no LowerBoundary=40 UpperThreshold=80 DataRate={bit_rate_gbps:g} Gbps \\
 LowerThreshold=20 UpperBoundary=60 TimePoints=800 AmplitudeResolution=0.001 V \\
 BERWidthHeight=1e-12 TimingBathTub=0.0 EyeMask="Eye_Probe1" UseEyeMask=no \\
 BERContour=list(1e-12,1e-11,1e-10) ExtrapolateBER=0 VoltageBathTub=0.5 \\
 DisableTransientOutput=no Save_BathtubQPlot=yes

TX:Tx_SingleEnded tx BitRate={bit_rate_gbps:g} Gbps Model="ADSTx" Vhigh={vhigh:g} V Vlow=0.0 V \\
 RiseFallTime=12.5 psec Mode=0 RegisterLength=15 Encoder=0 \\
 PostCursor[0]=1.0 TapInterval=0.5 EQMode=0

S_Port:S2P_Channel tx 0 rx 0 TSfile="{s2p_name}" TSfreq=freq Temp=25 \\
 CheckPassivity=no MinFileFreq=0 MaxFileFreq=1e12 EnforcePassivity=yes \\
 FileName="{s2p_name}" InterpMode="linear" ExtrapMode="interpMode"

Termination:Term_SingleEnded1 rx Load=50 Ohm
"""


def make_dds(dataset: str, bit_rate_gbps: float) -> str:
    return f"""defun _DDSobjectSaveRestore_()
{{
decl ddsId, ddoId, dssId, pageId, plotId, axisID, traceID, ddWinId;
ddsId = get_dds();
set(ddsId, "ddsFileVersion", 1.0);
ddoId = get_new(ddsId, "Object");
set(ddoId, "Path", dds_get_exec_path(what_file(0)));
set(ddoId, "Name", dds_get_exec_file(what_file(0)));
dssId = get(ddoId, "DatasetServer");
set(ddoId, "DefaultDataset", "{dataset}");
set(ddoId, "GridOn", 0);
pageId = get(ddoId, "CurrentPage");
if (pageId == NULL) pageId = get_first(ddoId, "Page");
if (pageId == NULL) pageId = get_new(ddoId, "Page");
plotId = get_new(pageId, "Plot");
set(plotId, "Title", "{bit_rate_gbps:g} Gbps Eye - HFSS 3D Layout Microstrip S2P");
set(plotId, "Left", -5200);
set(plotId, "Top", -200);
set(plotId, "Right", -500);
set(plotId, "Bottom", 2600);
axisID = get_new(plotId, "Axis", ddsXaxis, "X Axis");
if (axisID != NULL) {{
  set(axisID, "UserLabel", "Time");
  set(axisID, "AutoscaleOnOff", TRUE);
}}
axisID = get_new(plotId, "Axis", ddsYaxis, "Y Axis");
if (axisID != NULL) {{
  set(axisID, "UserLabel", "Voltage");
  set(axisID, "AutoscaleOnOff", TRUE);
}}
traceID = get_new(plotId, "Trace", "Waveform", "X Axis", "Y Axis");
if (traceID != NULL) {{
  set(traceID, "TraceType", ddsAutomaticTraceType);
  set(traceID, "Color", 1);
  set(traceID, "LineThick", 7);
}}
set(plotId, "InitPlot", 0);
set(pageId, "Name", "Eye");
set(pageId, "Uid", 1001);
set(ddoId, "UpdateAllExpressions", TRUE);
set(ddoId, "EnableExpressionUpdates", TRUE);
ddWinId = get_new(ddsId, "Window");
set(ddWinId, "Object", ddoId);
set(ddWinId, "CurrentPage", 1001);
set(ddWinId, "WindowPageOrder", list("Eye"));
}}

_DDSobjectSaveRestore_() ;
"""


def register_workspace_items(workspace_ads: Path) -> None:
    text = workspace_ads.read_text(encoding="utf-8", errors="replace")
    marker = '        <Folder Name="01_ReadMe">'
    block = """        <Folder Name="00_SIPI Microstrip 4Gbps">
            <Data_Display Name="microstrip_4gbps_eye.dds" />
            <Dataset Name="microstrip_4gbps_channel.ds" />
            <Log Name="microstrip_4gbps_channel_hpeesofsim.log" />
            <ConfigFile Name="microstrip_4gbps_channel.ckt" />
            <ConfigFile Name="README_SIPI_ADS.md" />
        </Folder>
"""
    if "00_SIPI Microstrip 4Gbps" in text:
        return
    if marker not in text:
        return
    workspace_ads.write_text(text.replace(marker, block + marker), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Create ADS ChannelSim workspace for the HFSS 3D Layout microstrip S2P.")
    parser.add_argument("--ads-dir", type=Path, default=DEFAULT_ADS)
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--s2p", type=Path, default=DEFAULT_S2P)
    parser.add_argument("--workspace", type=Path, default=DEFAULT_WORKSPACE)
    parser.add_argument("--bit-rate-gbps", type=float, default=DEFAULT_BIT_RATE_GBPS)
    parser.add_argument("--vhigh", type=float, default=DEFAULT_VHIGH)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    if not args.s2p.exists():
        raise FileNotFoundError(args.s2p)
    if not args.template.exists():
        raise FileNotFoundError(args.template)
    if not (args.ads_dir / "bin" / "hpeesofsim.exe").exists():
        raise FileNotFoundError(args.ads_dir / "bin" / "hpeesofsim.exe")

    if args.workspace.exists():
        if not args.overwrite:
            raise FileExistsError(f"{args.workspace} exists; pass --overwrite")
        shutil.rmtree(args.workspace)

    args.workspace.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(args.template, args.workspace)

    data_dir = args.workspace / "data"
    data_dir.mkdir(exist_ok=True)
    s2p_dst = data_dir / "microstrip_50ohm_fr4_1p6_hfss3dlayout.s2p"
    shutil.copy2(args.s2p, s2p_dst)

    netlist = make_netlist(s2p_dst.name, args.bit_rate_gbps, args.vhigh)
    netlist_path = args.workspace / "microstrip_4gbps_channel.ckt"
    netlist_path.write_text(netlist, encoding="utf-8")

    dds_path = args.workspace / "microstrip_4gbps_eye.dds"
    dds_path.write_text(make_dds("microstrip_4gbps_channel", args.bit_rate_gbps), encoding="utf-8")
    register_workspace_items(args.workspace / "workspace.ads")

    readme = args.workspace / "README_SIPI_ADS.md"
    readme.write_text(
        "\n".join(
            [
                "# SIPI ADS 4 Gbps ChannelSim Workspace",
                "",
                f"- ADS version root: `{args.ads_dir}`",
                f"- Source Touchstone: `{args.s2p}`",
                f"- Workspace: `{args.workspace}`",
                f"- Channel netlist: `{netlist_path.name}`",
                f"- Eye Data Display: `{dds_path.name}`",
                "",
                "Circuit intent:",
                f"- `Tx_SingleEnded` PRBS-like NRZ source at {args.bit_rate_gbps:g} Gbps, Vhigh={args.vhigh:g} V.",
                "- `S_Port:S2P_Channel` loads the HFSS 3D Layout 2-port Touchstone file.",
                "- `Eye_Probe1` is attached at the receiver node `rx`.",
                "- `Term_SingleEnded1` provides a 50 ohm receive load.",
                "",
                "Expected run command:",
                "```powershell",
                f"& '{args.ads_dir / 'bin' / 'hpeesofsim.exe'}' .\\{netlist_path.name}",
                "```",
                "",
            ]
        ),
        encoding="utf-8",
    )

    summary = {
        "ads_dir": str(args.ads_dir),
        "workspace": str(args.workspace),
        "source_s2p": str(args.s2p),
        "workspace_s2p": str(s2p_dst),
        "netlist": str(netlist_path),
        "dds": str(dds_path),
        "bit_rate_gbps": args.bit_rate_gbps,
        "vhigh_v": args.vhigh,
        "eye_probe": "Eye_Probe1 at rx",
    }
    summary_path = args.workspace / "microstrip_4gbps_ads_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
