from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path


DEFAULT_AEDT_EXE = r"C:\Program Files\ANSYS Inc\v251\AnsysEM\ansysedt.exe"


def default_aedt_exe() -> str:
    return os.environ.get("AEDT_EXE") or os.environ.get("ANSYSEDT_EXE") or DEFAULT_AEDT_EXE


def build_script(args: argparse.Namespace, script_path: Path) -> None:
    project = Path(args.project).resolve()
    csv_path = Path(args.csv).resolve()
    summary = Path(args.summary).resolve()
    expressions = []
    for i in range(1, args.ports + 1):
        for j in range(1, args.ports + 1):
            if args.expression_mode == "raw":
                expressions.append(f"S(Port{i},Port{j})")
            elif args.expression_mode == "db":
                expressions.append(f"dB(S(Port{i},Port{j}))")
            else:
                expressions.append(f"re(S(Port{i},Port{j}))")
                expressions.append(f"im(S(Port{i},Port{j}))")

    code = f'''# Auto-generated by export_hfss3dlayout_report_csv.py
import json
import os
import traceback
import ScriptEnv

PROJECT = r"{project}"
DESIGN = r"{args.design}"
SOLUTION = r"{args.solution}"
CSV = r"{csv_path}"
SUMMARY = r"{summary}"
REPORT = r"{args.report_name}"
EXPRESSIONS = {expressions!r}

out = {{
    "ok": False,
    "project": PROJECT,
    "design": DESIGN,
    "solution": SOLUTION,
    "csv": CSV,
    "expressions": EXPRESSIONS,
    "attempts": [],
}}

def try_delete(module, name):
    try:
        module.DeleteReports([name])
    except Exception:
        pass

try:
    ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
    oDesktop.RestoreWindow()
    oProject = oDesktop.OpenProject(PROJECT)
    oDesign = oProject.SetActiveDesign(DESIGN)
    oModule = oDesign.GetModule("ReportSetup")
    try_delete(oModule, REPORT)
    variations = [
        ["Domain:=", "Sweep"],
        ["Freq:=", ["All"]],
    ]
    try:
        oModule.CreateReport(
            REPORT,
            "Standard",
            "Rectangular Plot",
            SOLUTION,
            variations[0],
            variations[1],
            ["X Component:=", "Freq", "Y Component:=", EXPRESSIONS],
            [],
        )
        out["attempts"].append({{"method": "CreateReport", "ok": True}})
    except Exception as exc:
        out["attempts"].append({{"method": "CreateReport", "error": str(exc), "traceback": traceback.format_exc()}})
        raise
    try:
        csv_dir = os.path.dirname(CSV)
        if csv_dir and not os.path.isdir(csv_dir):
            os.makedirs(csv_dir)
        oModule.ExportToFile(REPORT, CSV, False)
        out["attempts"].append({{"method": "ExportToFile", "exists": os.path.exists(CSV), "size": os.path.getsize(CSV) if os.path.exists(CSV) else 0}})
        out["ok"] = os.path.exists(CSV) and os.path.getsize(CSV) > 0
    except Exception as exc:
        out["attempts"].append({{"method": "ExportToFile", "error": str(exc), "traceback": traceback.format_exc()}})
    try:
        out["available_solutions_standard"] = list(oModule.GetAvailableSolutions("Standard"))
    except Exception as exc:
        out["available_solutions_standard_error"] = str(exc)
    try:
        out["messages"] = list(oDesktop.GetMessages("", "", 2))
    except Exception:
        pass
except Exception as exc:
    out["error"] = str(exc)
    out["traceback"] = traceback.format_exc()
finally:
    with open(SUMMARY, "w") as f:
        json.dump(out, f, indent=2)
'''
    script_path.write_text(code, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export S-parameter report CSV from HFSS 3D Layout.")
    parser.add_argument("--project", required=True)
    parser.add_argument("--design", required=True)
    parser.add_argument("--solution", required=True)
    parser.add_argument("--ports", type=int, default=2)
    parser.add_argument("--expression-mode", choices=["raw", "ri", "db"], default="ri")
    parser.add_argument("--csv", required=True)
    parser.add_argument("--summary", required=True)
    parser.add_argument("--report-name", default="SParam_Export")
    parser.add_argument("--aedt-exe", default=default_aedt_exe())
    parser.add_argument("--non-graphical", action="store_true")
    args = parser.parse_args()

    summary = Path(args.summary).resolve()
    summary.parent.mkdir(parents=True, exist_ok=True)
    script_path = summary.with_suffix(".aedt_report_export.py")
    build_script(args, script_path)
    cmd = [args.aedt_exe]
    if args.non_graphical:
        cmd.append("-ng")
    cmd.extend(["-RunScriptAndExit", str(script_path)])
    cp = subprocess.run(cmd, capture_output=True, text=True)
    wrapper = {
        "cmd": cmd,
        "returncode": cp.returncode,
        "stdout": cp.stdout,
        "stderr": cp.stderr,
        "script": str(script_path),
        "summary": str(summary),
    }
    summary.with_suffix(".wrapper.json").write_text(json.dumps(wrapper, indent=2), encoding="utf-8")
    print(json.dumps(wrapper, indent=2))
    return cp.returncode


if __name__ == "__main__":
    raise SystemExit(main())
