from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path


DEFAULT_AEDT_EXE = r"C:\Program Files\ANSYS Inc\v251\AnsysEM\ansysedt.exe"


def default_aedt_exe() -> str:
    return os.environ.get("AEDT_EXE") or os.environ.get("ANSYSEDT_EXE") or DEFAULT_AEDT_EXE


def build_script(args: argparse.Namespace, script_path: Path) -> None:
    project = Path(args.project).resolve()
    summary = Path(args.summary).resolve()
    code = f'''# Auto-generated by inspect_aedt_design_native.py
import json
import os
import traceback
import ScriptEnv

PROJECT = r"{project}"
DESIGN = r"{args.design}"
SUMMARY = r"{summary}"

def safe(label, fn):
    try:
        value = fn()
        try:
            value = list(value)
        except Exception:
            pass
        out[label] = value
    except Exception as exc:
        out[label] = {{"error": str(exc)}}

def child_info(prefix, obj, depth=0):
    safe(prefix + ".name", lambda: obj.GetName())
    try:
        prop_names = list(obj.GetPropNames())
        out[prefix + ".props"] = prop_names
        values = {{}}
        for prop_name in prop_names:
            try:
                values[prop_name] = obj.GetPropValue(prop_name)
            except Exception as exc:
                values[prop_name] = {{"error": str(exc)}}
        out[prefix + ".prop_values"] = values
    except Exception as exc:
        out[prefix + ".props"] = {{"error": str(exc)}}
    safe(prefix + ".children", lambda: obj.GetChildNames())
    if depth <= 0:
        return
    try:
        for child_name in list(obj.GetChildNames()):
            child = obj.GetChildObject(child_name)
            key = prefix + "." + child_name.replace(" ", "_").replace(":", "_")
            child_info(key, child, depth - 1)
    except Exception as exc:
        out[prefix + ".child_error"] = str(exc)

out = {{"ok": False, "project": PROJECT, "design": DESIGN}}
try:
    ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
    oDesktop.RestoreWindow()
    oProject = oDesktop.OpenProject(PROJECT)
    oDesign = oProject.SetActiveDesign(DESIGN)
    out["project_name"] = oProject.GetName()
    out["design_name"] = oDesign.GetName()
    safe("design.children", lambda: oDesign.GetChildNames())
    for child_name in ["Analysis", "Excitations", "Boundaries", "Results"]:
        try:
            child_info("child." + child_name, oDesign.GetChildObject(child_name), 2)
        except Exception as exc:
            out["child." + child_name] = {{"error": str(exc)}}
    for module_name in ["SolveSetups", "ReportSetup", "Solutions", "AnalysisSetup"]:
        try:
            module = oDesign.GetModule(module_name)
            out["module." + module_name] = "ok"
            safe("module." + module_name + ".setups", lambda m=module: m.GetSetups())
            safe("module." + module_name + ".sweeps.Setup1", lambda m=module: m.GetSweeps("Setup1"))
            safe("module." + module_name + ".sweeps.Setup_8G_3xNyq", lambda m=module: m.GetSweeps("Setup_8G_3xNyq"))
            safe("module." + module_name + ".available_solutions", lambda m=module: m.GetAvailableSolutions())
            safe("module." + module_name + ".all_solution_names", lambda m=module: m.GetAllSolutionNames())
            safe("module." + module_name + ".available_report_types", lambda m=module: m.GetAvailableReportTypes())
        except Exception as exc:
            out["module." + module_name] = {{"error": str(exc)}}
    safe("messages", lambda: oDesktop.GetMessages("", "", 2))
    out["ok"] = True
except Exception as exc:
    out["error"] = str(exc)
    out["traceback"] = traceback.format_exc()
finally:
    with open(SUMMARY, "w") as f:
        json.dump(out, f, indent=2)
'''
    script_path.write_text(code, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Inspect AEDT design setup/solution tree through native ScriptEnv.")
    parser.add_argument("--project", required=True)
    parser.add_argument("--design", required=True)
    parser.add_argument("--summary", required=True)
    parser.add_argument("--aedt-exe", default=default_aedt_exe())
    parser.add_argument("--non-graphical", action="store_true")
    args = parser.parse_args()

    summary = Path(args.summary).resolve()
    summary.parent.mkdir(parents=True, exist_ok=True)
    script_path = summary.with_suffix(".inspect_aedt.py")
    build_script(args, script_path)
    cmd = [args.aedt_exe]
    if args.non_graphical:
        cmd.append("-ng")
    cmd.extend(["-RunScriptAndExit", str(script_path)])
    cp = subprocess.run(cmd, capture_output=True, text=True)
    wrapper = {
        "cmd": cmd,
        "returncode": cp.returncode,
        "stdout": cp.stdout,
        "stderr": cp.stderr,
        "script": str(script_path),
        "summary": str(summary),
    }
    summary.with_suffix(".inspect_wrapper.json").write_text(json.dumps(wrapper, indent=2), encoding="utf-8")
    print(json.dumps(wrapper, indent=2))
    return cp.returncode


if __name__ == "__main__":
    raise SystemExit(main())
