from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Open the imported HFSS 3D Layout project in AEDT GUI.")
    parser.add_argument(
        "--project",
        required=True,
        help="AEDT project file generated by the ODB++ import.",
    )
    parser.add_argument("--design", default=None, help="Design name to activate. Defaults to the imported design.")
    parser.add_argument("--version", default="2025.1")
    parser.add_argument(
        "--summary",
        required=True,
        help="Output summary JSON path.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    project = Path(args.project)
    if not project.exists():
        raise FileNotFoundError(project)

    from ansys.aedt.core import Hfss3dLayout

    h3d = Hfss3dLayout(
        project=str(project),
        design=args.design,
        version=args.version,
        non_graphical=False,
        new_desktop=True,
        close_on_exit=False,
    )

    summary = {
        "ok": True,
        "project_file": getattr(h3d, "project_file", str(project)),
        "project_name": getattr(h3d, "project_name", None),
        "design_name": getattr(h3d, "design_name", None),
        "aedt_version": args.version,
        "non_graphical": False,
        "note": "AEDT GUI session is intentionally left open.",
    }
    summary_path = Path(args.summary)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf8")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
