from __future__ import annotations

import argparse
import copy
import json
import os
import subprocess
from pathlib import Path


DEFAULT_AEDT_EXE = r"C:\Program Files\ANSYS Inc\v251\AnsysEM\ansysedt.exe"


def default_aedt_exe() -> str:
    return os.environ.get("AEDT_EXE") or os.environ.get("ANSYSEDT_EXE") or DEFAULT_AEDT_EXE


def q(path: str | Path) -> str:
    return str(path)


def make_hfss3dlayout_setup_arg(setup_name: str, adaptive_ghz: float) -> list:
    """Build a native AEDT HFSS 3D Layout setup argument list.

    The wrapper process is CPython, so it can use PyAEDT's shipped setup
    templates to generate the same argument list that ``Hfss3dLayout.create_setup``
    would send to ``SolveSetups.Add``. The generated list is then embedded into
    the ScriptEnv IronPython script.
    """
    try:
        from ansys.aedt.core.generic.data_handlers import _dict2arg
        from ansys.aedt.core.modules import setup_templates

        props = copy.deepcopy(setup_templates.HFSS3DLayout)
        props["Frequency"] = f"{adaptive_ghz}GHz"
        adaptive = props.get("AdaptiveSettings", {}).get("SingleFrequencyDataList", {}).get("AdaptiveFrequencyData")
        if isinstance(adaptive, dict):
            adaptive["AdaptiveFrequency"] = f"{adaptive_ghz}GHz"
        arg = ["NAME:" + setup_name]
        _dict2arg(props, arg)
        return arg
    except Exception:
        # Fallback is intentionally minimal; most environments should take the
        # PyAEDT-template path above. If this fallback fails, the summary will
        # show setup registration failure before any long solve starts.
        return [
            "NAME:" + setup_name,
            "SolveSetupType:=",
            "HFSS",
            "Frequency:=",
            f"{adaptive_ghz}GHz",
            "MeshSizeFactor:=",
            1.5,
            "DoAdaptive:=",
            True,
        ]


def make_hfss3dlayout_sweep_arg(
    sweep_name: str,
    start_ghz: float,
    stop_ghz: float,
    points: int,
    sweep_type: str = "Interpolating",
) -> list:
    """Build a native HFSS 3D Layout sweep argument list with frequency data.

    The HFSS 3D Layout native sweep table is populated through
    ``Sweeps/Data`` strings such as ``LINC 0.01GHz 6GHz 121``. Generic
    ``RangeStart`` and ``RangeEnd`` properties can create a visible sweep with
    no frequency row, which later exports only ``Last Adaptive``.
    """
    try:
        from ansys.aedt.core.generic.data_handlers import _dict2arg
        from ansys.aedt.core.modules import setup_templates

        props = copy.deepcopy(setup_templates.Sweep3DLayout)
        props.setdefault("Sweeps", {})["Variable"] = "Freq"
        props.setdefault("Sweeps", {})["Data"] = f"LINC {start_ghz}GHz {stop_ghz}GHz {points}"
        props["GenerateSurfaceCurrent"] = False
        props["SaveRadFieldsOnly"] = False
        props["UseQ3DForDC"] = False
        props["MaxSolutions"] = 250
        if sweep_type == "Discrete":
            props["FreqSweepType"] = "kDiscrete"
            props["EnforcePassivity"] = False
            props["AutoSMatOnlySolve"] = False
        else:
            props["FreqSweepType"] = "kInterpolating"
            props["EnforcePassivity"] = True
            props["AutoSMatOnlySolve"] = True
        arg = ["NAME:" + sweep_name]
        _dict2arg(props, arg)
        return arg
    except Exception:
        return [
            "NAME:" + sweep_name,
            ["NAME:Properties", "Enable:=", "true"],
            [
                "NAME:Sweeps",
                "Variable:=",
                "Freq",
                "Data:=",
                f"LINC {start_ghz}GHz {stop_ghz}GHz {points}",
                "OffsetF1:=",
                False,
                "Synchronize:=",
                0,
            ],
            "GenerateSurfaceCurrent:=",
            False,
            "SaveRadFieldsOnly:=",
            False,
            "SAbsError:=",
            0.005,
            "EnforcePassivity:=",
            sweep_type != "Discrete",
            "UseQ3DForDC:=",
            False,
            "MaxSolutions:=",
            250,
            "FreqSweepType:=",
            "kDiscrete" if sweep_type == "Discrete" else "kInterpolating",
        ]


def build_script(args: argparse.Namespace, script_path: Path) -> None:
    project = Path(args.project).resolve()
    touchstone = Path(args.touchstone).resolve()
    summary = Path(args.summary).resolve()
    setup_arg = make_hfss3dlayout_setup_arg(args.setup, args.stop_ghz)
    sweep_arg = make_hfss3dlayout_sweep_arg(args.sweep, args.start_ghz, args.stop_ghz, args.points, args.sweep_type)
    code = f'''# Auto-generated by run_aedt_native_export.py
import json
import os
import traceback
import ScriptEnv

PROJECT = r"{q(project)}"
DESIGN = r"{args.design}"
SETUP = r"{args.setup}"
SWEEP = r"{args.sweep}"
TOUCHSTONE = r"{q(touchstone)}"
SUMMARY = r"{q(summary)}"
RUN_SOLVE = {bool(args.run_solve)}
ENSURE_SETUP = {bool(args.ensure_setup)}
ENSURE_SWEEP = {bool(args.ensure_sweep)}
START_GHZ = {float(args.start_ghz)}
STOP_GHZ = {float(args.stop_ghz)}
POINTS = {int(args.points)}
SETUP_ARG = {repr(setup_arg)}
SWEEP_ARG = {repr(sweep_arg)}

summary = {{
    "ok": False,
    "project": PROJECT,
    "design": DESIGN,
    "setup": SETUP,
    "sweep": SWEEP,
    "touchstone": TOUCHSTONE,
    "run_solve": RUN_SOLVE,
    "ensure_setup": ENSURE_SETUP,
    "ensure_sweep": ENSURE_SWEEP,
    "start_ghz": START_GHZ,
    "stop_ghz": STOP_GHZ,
    "points": POINTS,
    "attempts": [],
}}

try:
    ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
    oDesktop.RestoreWindow()
    oProject = oDesktop.OpenProject(PROJECT)
    oDesign = oProject.SetActiveDesign(DESIGN)
    summary["project_name"] = oProject.GetName()
    summary["design_name"] = oDesign.GetName()
    try:
        summary["messages_before"] = list(oDesktop.GetMessages("", "", 2))
    except Exception as exc:
        summary["messages_before_error"] = str(exc)

    solve_setups = oDesign.GetModule("SolveSetups")
    existing_setups = []
    try:
        existing_setups = list(solve_setups.GetSetups())
    except Exception as exc:
        summary["get_setups_before_error"] = str(exc)
    summary["setups_before"] = existing_setups

    if ENSURE_SETUP and SETUP not in existing_setups:
        try:
            solve_setups.Add(SETUP_ARG)
            summary["add_setup"] = "called"
            oProject.Save()
        except Exception as exc:
            summary["add_setup_error"] = str(exc)
        try:
            existing_setups = list(solve_setups.GetSetups())
        except Exception as exc:
            summary["get_setups_after_add_error"] = str(exc)
            existing_setups = []
        summary["setups_after_add"] = existing_setups

    if SETUP not in existing_setups:
        summary["setup_registered"] = False
        summary["setup_blocker"] = "SolveSetups.GetSetups() does not include " + SETUP
    else:
        summary["setup_registered"] = True

    if ENSURE_SWEEP and summary.get("setup_registered"):
        try:
            existing_sweeps = []
            try:
                existing_sweeps = list(solve_setups.GetSweeps(SETUP))
            except Exception as exc:
                summary["get_sweeps_before_error"] = str(exc)
            summary["sweeps_before"] = existing_sweeps
            if SWEEP in existing_sweeps:
                try:
                    solve_setups.DeleteSweep(SETUP, SWEEP)
                    summary["delete_existing_sweep"] = "called"
                except Exception as exc:
                    summary["delete_existing_sweep_warning"] = str(exc)
            try:
                solve_setups.AddSweep(SETUP, SWEEP_ARG)
                summary["add_sweep"] = "called_template"
            except Exception as exc:
                summary["add_sweep_error"] = str(exc)
            try:
                summary["sweeps_after"] = list(solve_setups.GetSweeps(SETUP))
            except Exception as exc:
                summary["get_sweeps_after_error"] = str(exc)
            oProject.Save()
        except Exception as exc:
            summary["ensure_sweep_error"] = str(exc)

    if RUN_SOLVE and summary.get("setup_registered"):
        try:
            oDesign.Analyze(SETUP)
            summary["analyze_setup_result"] = "called"
        except Exception as exc:
            summary["analyze_setup_error"] = str(exc)
        for sweep_solution in [SETUP + " : " + SWEEP, SETUP + ":" + SWEEP]:
            try:
                oDesign.Analyze(sweep_solution)
                summary.setdefault("analyze_sweep_results", []).append({{"solution": sweep_solution, "result": "called"}})
            except Exception as exc:
                summary.setdefault("analyze_sweep_results", []).append({{"solution": sweep_solution, "error": str(exc)}})
    elif RUN_SOLVE:
        summary["analyze_setup_result"] = "skipped_setup_not_registered"

    out_dir = os.path.dirname(TOUCHSTONE)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir)

    try:
        rs = oDesign.GetModule("ReportSetup")
        try:
            summary["report_available_solutions_standard"] = list(rs.GetAvailableSolutions("Standard"))
        except Exception as exc:
            summary["report_available_solutions_standard_error"] = str(exc)
    except Exception as exc:
        summary["report_setup_module_error"] = str(exc)

    solution_names = []
    try:
        solution_names = list(oDesign.GetModule("SolveSetups").GetAllSolutionNames())
    except Exception as exc:
        summary["get_all_solution_names_error"] = str(exc)
    for candidate in [SETUP + " : " + SWEEP, SETUP + ":" + SWEEP, SETUP]:
        if candidate not in solution_names:
            solution_names.append(candidate)
    summary["solution_names_for_export"] = solution_names

    source_lists = []
    for solution in solution_names:
        source_lists.append([solution])
    source_lists.extend([[], ["Port1", "Port2"], ["All"]])
    freq_arg_lists = [["all"], ["All"], [], [START_GHZ, STOP_GHZ, POINTS], [str(START_GHZ) + "GHz", str(STOP_GHZ) + "GHz", POINTS]]

    for variation in ["", "Nominal"]:
        for sources in source_lists:
            for freq_args in freq_arg_lists:
                for renorm in [True, False]:
                    try:
                        oDesign.ExportNetworkData(
                            variation,
                            sources,
                            3,
                            TOUCHSTONE.replace("\\\\", "/"),
                            freq_args,
                            renorm,
                            50,
                            "S",
                            -1,
                            0,
                            15,
                            False,
                            False,
                            False,
                        )
                        exists = os.path.exists(TOUCHSTONE)
                        size = os.path.getsize(TOUCHSTONE) if exists else 0
                        attempt = {{
                            "variation": variation,
                            "sources": sources,
                            "freq_args": freq_args,
                            "renormalize": renorm,
                            "exists": exists,
                            "size": size,
                        }}
                        summary["attempts"].append(attempt)
                        if exists and size > 0:
                            summary["ok"] = True
                            raise SystemExit
                    except SystemExit:
                        raise
                    except Exception as exc:
                        summary["attempts"].append({{
                            "variation": variation,
                            "sources": sources,
                            "freq_args": freq_args,
                            "renormalize": renorm,
                            "error": str(exc),
                        }})
except SystemExit:
    pass
except Exception as exc:
    summary["error"] = str(exc)
    summary["traceback"] = traceback.format_exc()
finally:
    try:
        summary["messages_after"] = list(oDesktop.GetMessages("", "", 2))
    except Exception:
        pass
    with open(SUMMARY, "w") as f:
        json.dump(summary, f, indent=2)
'''
    script_path.write_text(code, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run AEDT native ScriptEnv export without PyAEDT app wrappers.")
    parser.add_argument("--project", required=True)
    parser.add_argument("--design", required=True)
    parser.add_argument("--setup", required=True)
    parser.add_argument("--sweep", required=True)
    parser.add_argument("--touchstone", required=True)
    parser.add_argument("--summary", required=True)
    parser.add_argument("--run-solve", action="store_true")
    parser.add_argument("--ensure-setup", action="store_true")
    parser.add_argument("--ensure-sweep", action="store_true")
    parser.add_argument("--start-ghz", type=float, default=0.1)
    parser.add_argument("--stop-ghz", type=float, default=12.0)
    parser.add_argument("--points", type=int, default=7)
    parser.add_argument("--sweep-type", choices=["Interpolating", "Fast", "Discrete"], default="Interpolating")
    parser.add_argument("--aedt-exe", default=default_aedt_exe())
    parser.add_argument("--non-graphical", action="store_true")
    args = parser.parse_args()
    if args.ensure_sweep:
        args.ensure_setup = True

    summary = Path(args.summary).resolve()
    summary.parent.mkdir(parents=True, exist_ok=True)
    script_path = summary.with_suffix(".aedt_export.py")
    build_script(args, script_path)

    cmd = [args.aedt_exe]
    if args.non_graphical:
        cmd.append("-ng")
    cmd.extend(["-RunScriptAndExit", str(script_path)])
    cp = subprocess.run(cmd, capture_output=True, text=True)
    wrapper = {
        "cmd": cmd,
        "returncode": cp.returncode,
        "stdout": cp.stdout,
        "stderr": cp.stderr,
        "script": str(script_path),
        "summary": str(summary),
    }
    wrapper_path = summary.with_suffix(".wrapper.json")
    wrapper_path.write_text(json.dumps(wrapper, indent=2), encoding="utf-8")
    print(json.dumps(wrapper, indent=2))
    return cp.returncode


if __name__ == "__main__":
    raise SystemExit(main())
